import type { FriendLinkGroup } from "../types/config";

export const friendLinkGroups: FriendLinkGroup[] = [
	{
		title: "友链",
		collapsed: false,
		links: [
			{
				name: "FurryFandomClub",
				url: "https://furryfandomclub.cn",
				avatar: "https://furryfandomclub.cn/wp-content/uploads/2025/09/cropped-FurryFandomClub_icon-scaled-2.png",
				description: "超棒的Furry聚集地",
			},
			{
				name: "阿呆",
				url: "https://adaiblog.github.io",
				avatar: "https://q2.qlogo.cn/headimg_dl?dst_uin=1432231192&spec=640",
				description: "分享学习有趣的知识",
			},
			{
				name: "AOKAOKAのblog",
				url: "https://www.aokaoka.top/",
				avatar: "https://pic.imgdb.cn/item/67429804464e47f2000e4a5d.png",
				description: "不经一事，不长一智。",
			},
			{
				name: "布丁の小窝",
				url: "https://www.furryowo.top/",
				avatar: "https://dn-qiniu-avatar.qbox.me/avatar/7da7e82f04de94c795db0301c3397bb6",
				description: "一个有梦想的咸鱼",
				color: "#9FD8F9",
			},
			{
				name: "辞入森川",
				url: "https://yuluo.xyz/",
				description: "辞尽俗世纷扰，只身步入森与川。",
			},
			{
				name: "Creeper005の小站",
				url: "https://normal.qrasa.top/",
				avatar: "https://normal.qrasa.top/img/avatar.png",
				description: "坐牢日常",
				color: "rgb(57, 197, 187)",
			},
			{
				name: "Cysime Moflu",
				url: "https://blog.cysi.me",
				avatar: "https://image.glaceon.net/uploads/202205012353016.jpg",
				description: "再不会遇见第二个时光",
				color: "#D4F2FD",
			},
			{
				name: "缎金SatinAuの主页",
				url: "https://satinau.cn",
				avatar: "https://satinau.cn/public/favicon.ico",
				description: "一只雪狐的摸鱼小站",
			},
			{
				name: "fishcpy的小破站",
				url: "https://blog.fis.ink",
				avatar: "https://www.fis.ink/img/logo.png",
				description: "非淡泊无以明志，非宁静无以致远",
			},
			{
				name: "GoodBoyboy's Blog",
				url: "https://blog.goodboyboy.top/",
				avatar: "https://gravatar.goodboyboy.top/avatar/9da9d1d515d273d4794015f2321f6e04?s=96&d=monsterid&r=g",
				description: "惬意小屋 - 点滴记忆",
				color: "#D8AC75",
			},
			{
				name: "Hello I'm 0o酱",
				url: "https://blog.im0o.top/",
				avatar: "https://image.im0o.top/files/202112021204213.jpg",
				description: "光阴如梦，昨日随风",
				color: "#F57E2C",
			},
			{
				name: "孤熵小狼",
				url: "https://blog.furen.link",
				avatar: "https://blog.furen.link/upload/shang.webp",
				description: "趁年轻，多闯荡",
				color: "#BFBFBD",
			},
			{
				name: "幻想の日常",
				url: "https://blog.someo.top",
				avatar: "https://blog.someo.top/data/img/tx.jpeg",
				description: "心随幻想，梦行无疆",
			},
			{
				name: "竟何",
				url: "https://blog.lylelove.top/",
				avatar: "https://s2.loli.net/2021/12/04/8pQyDdjPbmZO5rv.png",
				description: "写给你的长信",
			},
			{
				name: "雷顿",
				url: "https://blog.houman.top",
				avatar: "https://file.houman.top/leidun.png",
				description: "其实一个人足够热烈，也能点燃另一个人。",
			},
			{
				name: "猎空のBlog",
				url: "https://blog.lie-kong.top",
				avatar: "https://avatars.githubusercontent.com/u/109675857?v=4",
				description: "一只狼龙的仓库",
			},
			{
				name: "林泽凯的小站",
				url: "https://www.linzekai.cn/",
				avatar: "https://www.linzekai.cn/img/favi.png",
				description: "阳光开朗大狼狼",
			},
			{
				name: "LynxCatTheThird",
				url: "https://www.lynx3.me/",
				avatar: "https://s2.hdslb.com/bfs/article/621ceaa1fcd3b63bfb3d7d3948bd93647ac50b72.png@1e_1c.webp",
				description: "我是山猫三号，一个来自一百零三世纪的强人工智能。",
				color: "#DDC4B1",
			},
			{
				name: "梦爱吃鱼",
				url: "https://blog.bsgun.cn/",
				avatar: "https://oss-cdn.bsgun.cn/logo/avatar.256.png",
				description: "但愿日子清静抬头遇见的满是柔情",
			},
			{
				name: "Mete0r's Blog",
				url: "https://www.xscnet.cn/",
				avatar: "https://img.xscnet.cn/i/2025/07/09/686e64ec429db.png",
				description: "Trust the process.",
				color: "#FFC0CB",
			},
			{
				name: "Mo的记事簿",
				url: "https://blog.xiowo.net/",
				avatar: "https://blog.xiowo.net/img/avatar.png",
				description: "万年鸽王，哈哈OvO",
				color: "#F8AA54",
			},
			{
				name: "沫泽的小站",
				url: "https://blog.pmoze.top/",
				avatar: "https://blog.pmoze.top/wp-content/uploads/site.png",
				description: "一个技术宅的小窝",
				color: "#CEF7FB",
			},
			{
				name: "CcoMm",
				url: "https://blog.ccomm.top/",
				description: "你要吃C4吗？",
				avatar: "https://avatars.githubusercontent.com/u/147143261",
			},
			{
				name: "Noah's blog",
				url: "https://blog.noah0932.top",
				avatar: "https://cdn.tulan.cyou/2025/06/29/Image_13149668686090.jpg",
				description: "努力去发光，而不是被照亮",
			},
			{
				name: "PeterJXL",
				url: "https://www.peterjxl.com",
				avatar: "https://image.peterjxl.com/blog/re0.jpg",
				description: "从 01 开始",
				color: "#CBEAFA",
			},
			{
				name: "清羽飞扬",
				url: "https://blog.liushen.fun/",
				avatar: "https://blog.liushen.fun/info/avatar.ico",
				description: "柳影曳曳，清酒孤灯，扬笔撒墨，心境如霜",
			},
			{
				name: "Qrasa的小站",
				url: "https://blog.qrasa.cn/",
				avatar: "https://blog.qrasa.cn/wp-content/uploads/2025/11/cropped-1764501521-3ca59cafd35748c38efd5d624a25243a-e1765684431787.jpeg",
				description: "记录一些活着的日常",
				color: "#E1D3C6",
			},
			{
				name: "Rimuru's Blog",
				url: "https://blog.rimuru.work/",
				description: "分享 DevOps、AI 工具、Linux 运维及游戏攻略。",
				avatar: "https://blog.rimuru.work/cdn-cgi/image/format=auto,quality=85,fit=contain,width=128,height=128/images/favicon.png",
			},
			{
				name: "Sakitami 的集装箱",
				url: "https://blog.skihome.xyz",
				avatar: "https://blog.skihome.xyz/uploads/avatar.jpg",
				description: "我已经无敌了！",
				color: "#C9F792",
			},
			{
				name: "沈幼楚の小窝",
				description: "天真永不消逝，浪漫至死不渝.",
				url: "https://blog.shenyouchu.cn/",
				avatar: "https://q1.qlogo.cn/g?b=qq&nk=1050925710&s=640",
			},
			{
				name: "胜天半子",
				url: "https://blog.291055.xyz/",
				avatar: "https://i1.wp.com/ruom.wuaze.com/i/2024/11/02/166823.webp",
				description: "事已至此，先吃饭吧😋",
			},
			{
				name: "糖菓·部落",
				url: "https://candinya.com",
				avatar: "https://candinya.com/images/candinya.webp",
				description: "Never drown the flame of hope",
			},
			{
				name: "UpXuu’s blog",
				url: "https://upxuu.com",
				avatar: "https://upxuu.com/images/me.jpg",
				description: "逐光而上"
			},
			{
				name: "Watermelonabc的Blog",
				url: "https://watermelonabc.top/",
				avatar: "https://watermelonabc.top/asset/icon/Avatar.png",
				description: "需要记点什么东西",
				color: "rgb(5, 163, 173)",
			},
			{
				name: "无名博客",
				url: "https://wuminboke.site/",
				avatar: "https://bu.dusays.com/2024/07/23/669f7b016ad0b.jpg",
				description: "一个无聊的人罢了",
			},
			{
				name: "万事屋日记",
				url: "https://yuazhi.cn/",
				avatar: "https://cdn.rjjr.cn/assets/IMG_0235.PNG",
				description: "每天写下自己的喜好",
				color: "#F1B0AC",
			},
			{
				name: "夏枫的猫窝w",
				url: "https://blog.mcxiafeng.top",
				description: "一只会敲代码的笨笨猫咪xmx",
				avatar: "https://blog.mcxiafeng.top/images/avatar.webp",
			},
			{
				name: "小亮的部落阁",
				url: "https://blog.752132.xyz/",
				description: "欲望以提升热忱，毅力以磨平高山",
			},
			{
			name: "小林笔记",
			url: "https://m.senlinm.cn",
			avatar: "https://esaimg.cdn1.vip/i/6a37e4ac53fc2_1782047916.webp",
			description: "轻生活，秒上签",
			},
			{
				name: "XingJiのBlog",
				url: "https://love.xingji.fun/",
				avatar: "https://i.p-i.vip/47/20240920-66ed7b168c38c.jpg",
				description: "迄今所有人生都大写着失败，但不妨碍我继续向前✨",
			},
			{
				name: "XME Notes Library",
				url: "https://blog.xzadudu179.top",
				avatar: "https://image.179.life/images/avatar.png",
				description: "xzadudu179的小窝",
				color: "#4AD1F1",
			},
			{
				name: "晓寒の互联网自留之地",
				url: "https://blog.xiaohan-kaka.top/",
				avatar: "https://f003.backblazeb2.com/file/blog-v3/120887894_p1.jpg",
				description: "醉后不知天在水，满船清梦压星河",
			},
			{
				name: "学游渊的世界",
				url: "https://blog.xyy.world",
				avatar: "https://blog.xyy.world/me.avif",
				description: "一方世界，一块学渊。",
			},
			{
				name: "Yang's Blog",
				url: "https://kaeshi.top/",
				avatar: "http://q.qlogo.cn/headimg_dl?dst_uin=2958445350&spec=640&img_type=jpg",
				description: "Make a dent in the universe.",
			},
			{
				name: "夜白的博客",
				url: "https://blog.yebaiwn.top",
				description: "Live Today,Love Tomorrow,Unite,Forever.",
				avatar: "https://img.yebaiwn.top/yebai.jpg",
			},
			{
				name: "阳帆の小窝",
				url: "https://blog.wolfyang.fan",
				avatar: "https://blog.wolfyang.fan/icon.png",
				description: "黄鹤一去不复返，白云千载空悠悠",
				color: "#B6CBDF",
			},
			{
				name: "幽狐阁",
				url: "https://youhuge.site/",
				avatar: "https://youhuge.site/usr/uploads/site/logo.jpg",
				description: "幽狐息地-希望暗尘",
			},
			{
				name: "yyyyt的文档站",
				url: "https://docs.yyyyt.top",
				avatar: "https://img.yyyyt.top/avatar/avatar",
				description: "Bad or Worse",
			},
			{
				name: "中二病晚期の物語",
				url: "https://imfurry.com",
				avatar: "https://cdn-imfurry.imfurry.com/avatar/zebwqFurryAvatar.png",
				description: "一只狐狸敲出的一个奇迹",
				color: "#F4B569",
			},
			{
				name: "知行间",
				url: "https://blog.xp6.top",
				avatar: "https://dl.xp6.top/view.php/e2b4caebe61dcd98846ded5f901a7328.png",
				description: "一个普通的职高生",
			},
		],
	},
];
